# Generated by Django 3.2.7 on 2021-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmcolaborador', models.CharField(max_length=255)),
                ('imcolaborador', models.CharField(max_length=400)),
            ],
        ),
    ]
