# Generated by Django 3.2.7 on 2021-09-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_players_nmsetor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmCurso', models.CharField(max_length=255)),
                ('nmInstituicao', models.CharField(max_length=400)),
                ('nmPlayer', models.CharField(max_length=400)),
                ('nuHoras', models.IntegerField()),
                ('ptHoras', models.DecimalField(decimal_places=2, max_digits=2)),
                ('acWorkshop', models.BooleanField()),
                ('ptWorkshop', models.DecimalField(decimal_places=2, max_digits=2)),
                ('acImplementacao', models.BooleanField()),
                ('ptImplementacao', models.DecimalField(decimal_places=2, max_digits=2)),
                ('acComunik', models.BooleanField()),
                ('ptComunik', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
