# Generated by Django 3.2.7 on 2021-09-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='acFaculdade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cursos',
            name='nuMaterias',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='acComunik',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='acImplementacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='acWorkshop',
            field=models.BooleanField(default=False),
        ),
    ]
